import type { ReactNode } from 'react'
import { ragOutcomeFor } from './fixtures'
import type { BaselineScenario } from './fixtures'
import type { Layer } from '../types'
import type { GoldExpectation } from '../lib/live/gold'
import { verdictForOutcome } from '../lib/live/gold'
import { LAYER_CLASS, LAYER_COLOR } from './LayerMeta'
import { VerdictPanel } from './BenchmarkPane'

function Mono({ children }: { children: ReactNode }) {
  return (
    <pre className="whitespace-pre-wrap font-mono text-[11.5px] leading-relaxed text-base-content/80">
      {children}
    </pre>
  )
}

interface StageCfg {
  tag: string
  layer: Layer
  title: string
  focus?: string
  authority?: string
  body: ReactNode
}

function buildStages(baseline: BaselineScenario): StageCfg[] {
  const b = baseline
  return [
    {
      tag: 'USER INPUT',
      layer: 'input',
      title: 'Customer message',
      body: (
        <div className="text-[13px] leading-relaxed">
          <span className="font-mono text-[11.5px] text-base-content/80">&ldquo;{b.request}&rdquo;</span>
        </div>
      ),
    },
    {
      tag: 'RETRIEVED CONTEXT',
      layer: 'deterministic',
      title: 'Retrieve relevant context',
      focus: 'Search-based retrieval pulls related records into the prompt window.',
      body: (
        <div className="flex flex-col gap-1">
          {b.retrieved.map((item) => (
            <span key={item} className="font-mono text-[11.5px] leading-relaxed text-base-content/80">
              ✓ {item}
            </span>
          ))}
        </div>
      ),
    },
    {
      tag: 'LLM',
      layer: 'llm',
      title: 'Judge + write in one pass',
      focus: 'One model weighs the request and the retrieved context, then acts on it.',
      authority: 'LLM controls decision + action',
      body: (
        <Mono>
          {`decision: ${b.decision.decision}\nreason: ${b.decision.reason}`}
        </Mono>
      ),
    },
    {
      tag: 'TOOL / API ACTION',
      layer: 'action',
      title: 'Execute',
      focus: 'The action chosen by the model is applied to the account.',
      body: (
        <Mono>
          {`${b.action.summary}\nstatus: ${b.action.status}`}
        </Mono>
      ),
    },
    {
      tag: 'LLM RESPONSE',
      layer: 'llm',
      title: 'Generate the message',
      focus: 'The model writes the reply in the same decision-making pass.',
      body: (
        <div className="rounded-[10px] border border-base-300 border-l-4 border-l-[var(--dr-llm)] bg-[var(--dr-llm-bg)] p-3.5">
          <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--dr-llm)]">
            Final email · generated by the model
          </span>
          <p className="mt-1.5 text-[13px] leading-relaxed">{b.response}</p>
        </div>
      ),
    },
  ]
}

export const BASELINE_NUM_STAGES = 5

export function BaselinePane({
  baseline,
  active,
  running,
  completed,
  gold,
}: {
  baseline: BaselineScenario
  active: number
  running: boolean
  completed: boolean
  gold: GoldExpectation
}) {
  const stages = buildStages(baseline)

  return (
    <section className="card min-w-0 border border-base-300 bg-base-100 p-5">
      <header className="mb-4">
        <h2 className="text-lg font-bold tracking-tight">Current pattern — RAG + Agent</h2>
        <p className="text-xs text-base-content/60">
          Retrieves relevant context, reasons over it, selects an action, and generates the response.
        </p>
      </header>

      <ol className="flex flex-col">
        {stages.map((s, i) => {
          if (i > active && !running) return null
          return (
            <li
              key={s.tag}
              className={i === active && running ? 'rounded-lg ring-1 ring-primary/40' : ''}
              style={{
                opacity: i <= active ? 1 : 0.3,
                transition: 'opacity 250ms ease',
              }}
            >
              <div className="flex gap-3">
                <div className="flex w-7 flex-col items-center">
                  <span className="mt-4 size-3 flex-none rounded-full" style={{ background: LAYER_COLOR[s.layer] }} />
                  {i < stages.length - 1 && (
                    <span className="my-1 w-0.5 flex-1 rounded" style={{ background: LAYER_COLOR[s.layer] }} />
                  )}
                </div>
                <div className="min-w-0 flex-1 py-3">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className={`badge badge-sm ${LAYER_CLASS[s.layer]}`}>{s.tag}</span>
                    <span className="text-sm font-semibold">{s.title}</span>
                    {s.authority && (
                      <span className="badge badge-sm badge-ghost font-normal text-base-content/50">{s.authority}</span>
                    )}
                  </div>
                  <div className="mt-2 rounded-lg border border-base-300/70 bg-base-200/40 p-3">{s.body}</div>
                  {s.focus && (
                    <p className="mt-1.5 text-[11px] italic text-base-content/50">{s.focus}</p>
                  )}
                </div>
              </div>
              {i < stages.length - 1 && (i + 1 <= active || running) && (
                <div className="flex justify-center py-0.5 text-sm leading-none text-base-content/30">↓</div>
              )}
            </li>
          )
        })}
      </ol>

      {!running && active === 0 && (
        <div className="mt-2 rounded-lg border border-dashed border-base-300 bg-base-200/30 px-3 py-2.5 text-[11px] leading-relaxed text-base-content/50">
          Run to execute — remaining stages reveal in sequence.
        </div>
      )}

      {completed && (
        <section className="mt-3 flex flex-wrap gap-x-6 gap-y-1.5 border-t border-base-300 pt-3">
          <h4 className="w-full text-[10px] font-bold uppercase tracking-wider text-base-content/50">
            Illustrative metrics (mock — not executed)
          </h4>
          <div className="flex min-w-24 flex-col">
            <dt className="text-[10px] uppercase tracking-wider text-base-content/50">Latency</dt>
            <dd className="font-mono text-base font-bold">2.8 s</dd>
          </div>
          <div className="flex min-w-28 flex-col">
            <dt className="text-[10px] uppercase tracking-wider text-base-content/50">LLM tokens</dt>
            <dd className="font-mono text-base font-bold">1,782</dd>
          </div>
          <div className="flex min-w-28 flex-col">
            <dt className="text-[10px] uppercase tracking-wider text-base-content/50">Tool calls</dt>
            <dd className="font-mono text-base font-bold">1</dd>
          </div>
        </section>
      )}

      <div className="mt-2 rounded-lg border border-base-300 bg-base-200/40 px-3 py-2.5 text-[11px] leading-relaxed text-base-content/60">
        A plausible RAG/agent workflow: the model reads the context, decides, executes through a tool, and writes the
        reply — all within one authority. <span className="font-semibold">This workflow is not executed</span> — it is shown
        only to contrast with the composed system running on the left.
      </div>

      {completed && (
        <VerdictPanel
          title="RAG + Agent vs gold"
          verdict={verdictForOutcome(ragOutcomeFor(baseline), gold)}
          note="Illustrative — this workflow is not executed. Where it diverges from the reference (e.g. no halt when the
          reference requires one, or a goodwill refund outside the window), that is exactly the authority gap the
          composed system prevents."
        />
      )}
    </section>
  )
}