import { useState } from 'react'
import summaryMd from '../../eval_results_summary.md?raw'
import { BenchmarkMatrix } from './BenchmarkMatrix'
import { AuthorityBoundaries } from './AuthorityBoundaries'
import { Markdown } from './Markdown'

function CopyButton({ text }: { text: string }) {
  const [state, setState] = useState<'copy' | 'copied'>('copy')
  return (
    <button
      type="button"
      className="btn btn-ghost btn-xs font-mono"
      onClick={() => {
        void navigator.clipboard?.writeText(text).then(() => {
          setState('copied')
          window.setTimeout(() => setState('copy'), 1500)
        })
      }}
    >
      {state === 'copy' ? 'copy' : 'copied ✓'}
    </button>
  )
}

export function ResultsPage() {
  return (
    <section className="flex flex-col gap-6">
      <header className="flex flex-col gap-2">
        <h2 className="text-xl font-bold tracking-tight">Evaluation Results</h2>
        <p className="max-w-3xl text-sm text-base-content/70">
          Full results of the 20-scenario empirical benchmark. The reference summary
          documents the methodology, the per-architecture numbers, and the fail-closed safety findings.
        </p>
      </header>

      <BenchmarkMatrix />

      <AuthorityBoundaries />

      <section className="card border border-base-300 bg-base-100 p-4">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-base-300/60 pb-3">
          <div>
            <h2 className="text-sm font-semibold uppercase tracking-wider text-base-content/70">
              Reference summary · eval_results_summary.md
            </h2>
            <p className="text-xs text-base-content/55">
              The markdown document also lives at the repo root and can be read as a file.
            </p>
          </div>
          <CopyButton text={summaryMd} />
        </div>
        <div className="mt-3 max-h-[600px] overflow-auto rounded-lg border border-base-300 bg-base-200/40 p-4 sm:p-5">
            <Markdown text={summaryMd} />
          </div>
      </section>

      <footer className="text-[11px] text-base-content/45">
        Results generated by the eval harness in scripts/eval.ts.
      </footer>
    </section>
  )
}